keywords = {
"All categories":0,
"Arts & Entertainment":3,
"Autos & Vehicles":47,
"Beauty & Fitness":44,
"Books & Literature":22,
"Business & Industrial":12,
"Computers & Electronics":5,
"Finance":7,
"Food & Drink":71,
"Games":8,
"Health":45,
"Hobbies & Leisure": 65,
"Home & Garden":11,
"Internet & Telecom":13,
"Jobs & Education":958,
"Law & Government":19,
"News":16,
"Online Communities":299,
"People & Society":14,
"Pets & Animals":66,
"Real Estate":29,
"Reference":533,
"Science":174,
"Shopping":18,
"Sports":20,
"Travel":67
}
